#!/usr/bin/env bash
# This script displays the contents of the file "/etc/passwd"
# Displays only username,user id and Home directory path for the user

while read -r passwd;
do
	echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
