#!/usr/bin/env bash
# The script display numbers from 1 to 20 together with the following
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration

total=1

while [ $total -le 20 ]
do
	echo "$total"
	case $total in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( total++ ))
done
